### PR TITLE
docs: accountV3 documentation

### LINKED ISSUE #2: ODHack: Document the AccountV3 Contract
Description: 
This documentation will serve as a reference for developers and users who want to understand the AccountV3.

**Goals:**

- Explain the purpose of the AccountV3 contract.
- Document the available functions

**References:**

- Link to existing documentation: https://docs.tbaexplorer.com/starknet-tokenbound-sdk/introduction-to-tokenbound
- Link to the AccountV3 contract code: https://github.com/horuslabsio/TBA/blob/v3/src/accountV3/accountV3.cairo
- New to contract documentations? Check out this sample docs as a guide: https://contracts-v2-docs.lens.xyz/contracts/libraries/ProfileLib.sol/library.ProfileLib

### PR DESCRIPTION
**Pull request by Iwueseiter**
resolves #2

### CODE REVIEW

**Review by VictoriaAde — CHANGES_REQUESTED** [review]
This is good!
Please add another section that explains the distinct difference between the V2 and V3, so developers would understand on a broader/deeper level what changed in this version.

**Comment by Iwueseiter** [comment]
Hi @VictoriaAde please review.

**Review by VictoriaAde — APPROVED** [review]

**Comment by VictoriaAde** [comment]
This looks great! 👏 
Thank you for your contribution @Iwueseiter.

**Comment by Iwueseiter** [comment]
> This looks great! 👏
> Thank you for your contribution @Iwueseiter.

Thank youu 😊

**Pull request merged**
