### PR TITLE
docs: permissionable component documentation

### LINKED ISSUE #6: ODHack: Document the Permissionable component
Description: 
This documentation will serve as a reference for developers and users who want to understand the functionality of the Permissionable component. 

**Goals:**

- Explain the purpose of the Permissionable component.
- Document the available functions.

**References:**

- Link to existing documentation: https://docs.tbaexplorer.com/starknet-tokenbound-sdk/introduction-to-tokenbound
- Link to the code: https://github.com/horuslabsio/TBA/blob/v3/src/components/permissionable/permissionable.cairo
- New to contract documentations? Check out this sample docs as a guide: https://contracts-v2-docs.lens.xyz/contracts/libraries/ProfileLib.sol/library.ProfileLib

### PR DESCRIPTION
**Pull request by Naomi-Gift**
Resolves #6

### CODE REVIEW

**Review by VictoriaAde — CHANGES_REQUESTED** [review]
What you have here is different from the contract code
https://github.com/horuslabsio/TBA/blob/v3/src/components/permissionable/permissionable.cairo

**Comment by Naomi-Gift** [comment]
> What you have here is different from the contract code https://github.com/horuslabsio/TBA/blob/v3/src/components/permissionable/permissionable.cairo

Alright ma’am I’ll work on it again
I think I worked on the wrong contract

**Comment by Naomi-Gift** [comment]
@VictoriaAde Can you review please.

**Review by VictoriaAde — APPROVED** [review]

**Comment by VictoriaAde** [comment]
Looks great! 🎉  
Thank you for your contribution.

**Pull request merged**
