### PR TITLE
Update Signatory.md

### PR DESCRIPTION
**Pull request by zleypner**
This PR draft introduces comprehensive documentation for the Signatory component, outlining its purpose and detailing the available functions. The aim is to provide clarity and serve as a reference for developers and users interacting with the component.

If you have any feedback, I will be glad to proceed with new updates

### CODE REVIEW

**Review by VictoriaAde — CHANGES_REQUESTED** [review]
Nice work. 
I noticed you used a lot of _ERC-6551_ in the documentation, you can also use **Tokenbound Account** in some places that requires it.

**Comment by zleypner** [comment]
Thank you for your feedback! I will use Tokenbound Account.

**Review by zleypner — COMMENTED** [review]
I have added the information regarding the TBA

**Comment by zleypner** [comment]
Should I remove some of the lines in the Files for Reference?

**Comment by VictoriaAde** [comment]
> Should I remove some of the lines in the Files for Reference?

This is good to go.

**Review by VictoriaAde — APPROVED** [review]

**Comment by VictoriaAde** [comment]
Thank you for your contribution.

**Pull request merged**
